// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bifdekugrptxrfsylanz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZmRla3VncnB0eHJmc3lsYW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4MzM3OTEsImV4cCI6MjA1MDQwOTc5MX0.wkdP2FfXYg8QSksu5pX9cFxxksNTdDFXUPnZRH4DPAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);